### ISSUE TITLE
Feature Request: The ability to pinpoint referenced files or scripts using a Goto button just like Assembly for Halo

### ISSUE THREAD

**Issue by Phantom-Aspekt** [SteezCram/PboViewer#3]
Being New to modding in the Arma series I'm finding the generally massive amount of fragmentation and script spaghetti difficult to get the hang of, I'm so used to using tools like Guerilla or Assembly for Halo that Arma feels 20 years behind. I'm currently tring to port 3 sided Mountain Warfare CTI form Arma 2 OA to Arma 3 and have had to look through multiple PBOs for the required files and scripts just for that one mission.

Windows 10, non specific.

Having the ability to set the game install locations for supported Arma titles and have a list in a portion of the window on the left with PBO files found in the install folders with the folder names as headders in a collapsible menu.

For example: 
[+] Arma 2 Operation Arrowhead
---[+] Common (PBO location)
---[+] Expansion
------[+] Addons (PBO location)
[+] Arma 3
---[+] Addons (PBO location)
---[+] Expansion
------[+] Addons (PBO location)
---[+] GM
------[+] Addons (PBO location)

Just to sweeten the layout even more be able to locate a referenced addon or file with one click, for example this line in config.cpp from the warfare2.pbo of Arma 2 Operation Arrowhead

class CfgPatches
{
	class Warfare2
	{
		units[] = {};
		weapons[] = {};
		requiredAddons[] = {"CA_Missions_SecOps"};
		requiredVersion = 0.1;
	};
};

Having a small window that mentions required addons and a Goto button next to it that should take you directly to the referenced PBO exactly like Assembly does for Tag files in the Halo engine would be an absolute gamechanger.

See here a referenced Tag in the Assembly with a Goto button at the arrow.
![Assembly 1](https://user-images.githubusercontent.com/85217420/127729556-c49b9c48-df28-424e-9190-08788ed94eed.png)

After clicking the button a new tab opens up with the referenced file contents!
![Assembly 2](https://user-images.githubusercontent.com/85217420/127729569-257885b9-1b69-424b-bfef-1b11ed40777d.png)

After scrolling to the bottom of the tag we find another tag that is referenced and another button to lead us.
![Assembly 3](https://user-images.githubusercontent.com/85217420/127729917-065fa246-b957-46b0-adc7-f2e456b7807b.png)

Another new tab and all the data for it
![Assembly 4](https://user-images.githubusercontent.com/85217420/127729929-5805a38a-e7a0-4012-ac4e-f5efc32cd506.png)

A future idea but probably way beyond the scope of this tool and possibly not even possible for Arma. Halo tag files in Assembly are modified using plugins which give you an easy to use UI to quickly modify all common variables of a tag file and directly reference them. 
For example a Light tag plugin will be different to a Weapon tag plugin but a Weapon tag can reference a Light tag as the light will be emitted during a firing effect
Here is a shader_model tag plugin for Assembly
![Assembly 5](https://user-images.githubusercontent.com/85217420/127730093-b4c1794e-e167-4abf-9ddb-1eef554e45ac.png)

The way I'm thinking about this whole thing is have the PBO files act sort of like .map files from the Halo engine and have the ability to use a full GUI system to quickly add, modify and reference files just like you would using Guerilla (the original development tool for the Halo engine) then turn it into a single PBO file ready to go in the arma engine without painstakingly finding and typing out loads of code to make things work. Probably wishful thinking but you'll never know if it's possible if you don't ask 🤷‍♂️

**Comment by SteezCram** [comment]
Hello, your request is very interesting but I found two major problems with your current implementation:
- The software is currently not designed to handle it and it would require a huge amount of time to mimic it
- It will be very slow to search in many PBO, especially if I add the possibility to check the original PBO of Arma 3

I think the file type are designed completely differently, the PBO format is just an archive readable by Arma 3. That means when you need to find the information you need to loop to all the files contained in the archive and read them entirely. Currently, I use few tricks to enable file watching since I unpack the PBO when you open it and remove the folder when you exit it.

I will try to make something to make something to find by reference (i.e a filename or a some text) through a directory.

**Comment by Phantom-Aspekt** [comment]
I figured it would be way beyond the original scope of this project and I obviously have little understanding on how the Arma engine works even though I've spent countless hours playing it haha. 

I didn't realize that it needs to unpack to see the .PBO contents, I guess there is a huge difference between the Halo .map files which have almost everything in the one file except for textures and sounds etc which go in separate .map files unless level specific. 
I wonder if or when a referencing tool gets implemented it could speed up the search without extracting the whole PBO by only extracting the config.cpp from the PBOs and cross referencing using those?

**Comment by SteezCram** [comment]
The config.pbo doesn't contain anything about the reference, Arma 3 will loop to all the .hpp files to find all the new models since they implement the same config class name: CfgVehicles.

For a huge modpack it can take some time to load all the config files and scripts. Plus I need a config parser which is difficult to make.
